ALTER TABLE loans ADD COLUMN IF NOT EXISTS late_fee_mode TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE loans ADD COLUMN IF NOT EXISTS late_fee_amount NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS late_fee_note TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS late_fee_updated_at TIMESTAMPTZ;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS late_fee_updated_by UUID REFERENCES users(id);
